#Include "totvs.ch"

/*---------------------------------------------------------------------------+
!                             FICHA TECNICA DO PROGRAMA                      !
+------------------+---------------------------------------------------------+
!Descricao         ! Ponto de Entrada na tela de liberacao/aprovacao de      !
!                  ! documentos de entrada e pedidos de compras              !
!                  ! 1. Utilizado para incluir um botao na tela de liberacao !
!                  !    com a opcao para visualizar o pedido de compras      !
+------------------+---------------------------------------------------------+
!Autor             ! Gustavo Schepp                                          !
+------------------+---------------------------------------------------------+
!Data de Criacao   ! 12/2012                                                 !
+------------------+--------------------------------------------------------*/

User Function MT097BUT
A097Visual(,,2)
Return