#Include "totvs.ch"

/*---------------------------------------------------------------------------+
!                             FICHA TECNICA DO PROGRAMA                      !
+------------------+---------------------------------------------------------+
!Descricao         ! Ponto de Entrada na tela de liberacao/aprovacao de      !
!                  ! documentos de entrada e pedidos de compras              !
!                  ! 1. Permite que NAO seja considerada a Filial na rotina  !
!                  !    de Liberação de Documentos.                          !
+------------------+---------------------------------------------------------+
!Autor             ! Gustavo                                                 !
+------------------+---------------------------------------------------------+
!Data de Criacao   ! 12/2012                                                 !
+------------------+--------------------------------------------------------*/

User Function MT097LBF
Return(.f.)