#INCLUDE "PROTHEUS.CH"
#INCLUDE "RWMAKE.CH"

/*
FUNCAO PARA RETORNAR O NOME DO CLIENTE OU FORNECEDOR NO BROWSE DA ROTINA DE DOCUMENTO DE SAIDA. 
UTILIZADO NO INICIALIZADOR PADRAO DO CAMPO C9_NOMCLI - Inicializador Browser - EXECBLOCK("BUT002",.T.,.T.)
*/

User Function BUT002

_lRet := ""
       
SC5->(DbSetOrder(1))

If SC5->(DbSeek(xFilial("SC5")+SC9->C9_PEDIDO))
	If SC5->C5_TIPO $'NCIP'
		_lRet := POSICIONE("SA1",1,xFilial("SA1")+SC9->C9_CLIENTE+SC9->C9_LOJA,"A1_NOME")
	Else
    	_lRet := POSICIONE("SA2",1,xFilial("SA2")+SC9->C9_CLIENTE+SC9->C9_LOJA,"A2_NOME")
	EndIf
EndIf    

//IIF(SC5->C5_TIPO$'NCIP',POSICIONE("SA1",1,xFilial("SA1")+SC5->C5_CLIENTE+SC5->C5_LOJACLI,"A1_NOME"),POSICIONE("SA2",1,xFilial("SA2")+SC5->C5_CLIENTE+SC5->C5_LOJACLI,"A2_NOME"))

Return(_lRet)
